version: "3"
services:
  web:
    build: .
    ports:
      - "127.0.0.1:8000:8000"
    volumes:
      - .:/app
    depends_on:
      - redis
    networks:
      - default
      - webtronics
  pg:
    image: postgres:14
    ports:
      - 127.0.0.1:5432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
    volumes:
      - pg-data:/var/lib/postgresql/data
      - .src/db/dumps/create_second_db.sh:/docker-entrypoint-initdb.d/create_second_db.sh
    networks:
      - default
      - webtronics
  redis:
    image: redis:latest
    container_name: webtronics-redis
    ports:
      - "127.0.0.1:6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - default
      - webtronics

volumes:
  pg-data:
    driver: local
  redis-data:
    driver: local

networks:
  default:
  webtronics:
    external: true
